# Generated by Django 2.2 on 2019-06-11 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PokemonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewtitle', models.CharField(max_length=255)),
                ('reviewdate', models.DateField()),
                ('reviewtext', models.TextField()),
                ('pokemonname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PokemonApp.Pokemon')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'reviews',
                'db_table': 'review',
            },
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='chargemovenum',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='fastmovenum',
        ),
        migrations.RemoveField(
            model_name='pokemontype',
            name='pokemontype2',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='pokemonname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PokemonApp.Pokemon'),
        ),
        migrations.DeleteModel(
            name='ChargeMove',
        ),
        migrations.DeleteModel(
            name='FastMove',
        ),
    ]
