# Generated by Django 2.2 on 2019-06-12 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonApp', '0003_auto_20190612_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='chargemovenum',
            new_name='attacknum',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='fastmovenum',
            new_name='defensenum',
        ),
    ]
